---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillpulse
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    app: frontend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      