apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillpulse
  namespace: argocd

spec:
  project: skillpulse

  destination:
    server: https://kubernetes.default.svc
    namespace: skillpulse

  source:
    repoURL: https://github.com/Sandippatil6696/github-actions-kubernetes-masterclass.git
    targetRevision: feat-gitops
    path: k8s

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true