name: Build and push

on:
  workflow_call:
    inputs:
      backend:
        required: true
        type: string
      frontend:
        required: true
        type: string
    outputs:
      sha_short:
        value: ${{ jobs.prepare.outputs.sha_short }}
   
permissions:
  contents: write

jobs:
    prepare:
      runs-on: ubuntu-latest
      outputs:
        sha_short: ${{ steps.tag.outputs.sha_short }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Shorten image tag
          id: tag
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  
    
  # ── Build backend only if backend changed
    build-backend:
        needs: prepare
        if: ${{ inputs.backend == 'true' }}
        runs-on: ubuntu-latest
        steps:
            
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: login to docker hub 
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: build and push 
              uses: docker/build-push-action@v6
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                       ${{ vars.DOCKERHUB_USER }}/skillpulse-backend:latest 
                       ${{ vars.DOCKERHUB_USER }}/skillpulse-backend:${{ needs.prepare.outputs.sha_short }}
                cache-from: type=gha,scope=skillpulse-backend
                cache-to: type=gha,mode=max,scope=skillpulse-backend

    # ── Build frontend only if frontend changed ───────────────────
    build-frontend:
      needs: prepare
      if: ${{ inputs.backend == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push frontend
          uses: docker/build-push-action@v6
          with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            tags: |
              ${{ vars.DOCKERHUB_USER }}/skillpulse-frontend:latest
              ${{ vars.DOCKERHUB_USER }}/skillpulse-frontend:${{ needs.prepare.outputs.sha_short }}
            cache-from: type=gha,scope=skillpulse-frontend
            cache-to: type=gha,mode=max,scope=skillpulse-frontend       