name: CI-DevSecOps
on:
  push:
    branches: [feat-gitops]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'k8s/**'
      - 'terraform/**'
      - 'Makefile' 
      - '.gitignore' 
      - 'setup.sh'
  workflow_dispatch:
  
permissions:
  contents: write   # ← required to update manifest and commit back
  actions: read           # ← required by dependency-scan-frontend (trivy)
  security-events: write

jobs:

   # ── Detect changes first ───────────────────────────────────────
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: HEAD~1
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Debug outputs       
        run: |
          echo "backend=${{ steps.filter.outputs.backend }}"
          echo "frontend=${{ steps.filter.outputs.frontend }}"

  # ── Stage 1: parallel ─────────────────────────────────────────
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml
    secrets: inherit

  dependancy-scan:
    uses: ./.github/workflows/dependancy-scan.yml

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml

  # ── Stage 2: build and push image only ────────────────────────
  build-and-push:
    needs: [detect-changes, code-quality, secret-scan, dependancy-scan, docker-lint]
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
    with:
      backend: ${{ needs.detect-changes.outputs.backend }}
      frontend: ${{ needs.detect-changes.outputs.frontend }}
     
 
  # ── Stage 3: scan → if clean → update manifest ────────────────
  image-scan:
    needs: [build-and-push,detect-changes]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
    with:
      sha_short: ${{ needs.build-and-push.outputs.sha_short }}
      backend: ${{ needs.detect-changes.outputs.backend }}
      frontend: ${{ needs.detect-changes.outputs.frontend }}