name: Code-Quality

on:
    push:
        branches: [feat-gitops]
        paths-ignore:
          - 'k8s/**'
          - 'docs/**'
          - '**/*.md'
    workflow_dispatch:


jobs:
  validate-backend-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
        - name: checkout code 
          uses: actions/checkout@v4

        - name: setup go 
          uses: actions/setup-go@v5
          with:
            go-version: 1.26.3
            cache: true 

        - name: Install golangci-lint from binary
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.9.0

        - name: install dependencies
          run: go mod tidy

        - name: run go lint
          run: golangci-lint run ./...

  validate-frontend-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
        - name: checkout code 
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        
        - name: Install Lint Tools
          run: |
            npm install --save-dev \
              eslint \
              @eslint/js \
              stylelint \
              stylelint-config-standard \
              htmlhint
        
        - name: Lint JavaScript
          run: npx eslint .

        - name: Lint CSS
          run: npx stylelint "**/*.css"

        - name: Lint HTML
          run: npx htmlhint "**/*.html"