name: Code-Quality

on:
    push:
        branches: [feat-gitops]
        paths-ignore:
          - 'k8s/**'
          - 'docs/**'
          - '**/*.md'
    workflow_dispatch:


jobs:
  validate-backend-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
        - name: checkout code 
          uses: actions/checkout@v4

        - name: setup go 
          uses: actions/setup-go@v5
          with:
            go-version: 1.26.3
            cache: true 

        - name: Install golangci-lint from binary
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.9.0

        - name: install dependencies
          run: go mod tidy

        - name: run go lint
          run: golangci-lint run ./...

  validate-frontend-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
        - name: checkout code 
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Run Super-Linter
          uses: super-linter/super-linter@v5
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VALIDATE_HTML: true
            VALIDATE_CSS: true
            VALIDATE_JAVASCRIPT_ES: true
