name: Dependency-Scan

on:
    push:
        branches: [feat-gitops]
        paths-ignore:
          - 'k8s/**'
          - 'docs/**'
          - '**/*.md'
    workflow_dispatch:

jobs:
  dependency-scan-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.3
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Install dependency
        run: go mod tidy
 
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
 
      - name: Run govulncheck
        run: govulncheck ./...


  dependency-scan-frontend:
    runs-on: ubuntu-latest
    permissions:
      security-events: write   
      actions: read            # ← required to read workflow info
      contents: read
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            trivy-db-${{ runner.os }}-
          save-always: true
 
      - name: Run Trivy on frontend (JS files)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: frontend/
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table
          