name: Lint Dockerfiles

on:
  workflow_call:


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint ${{ matrix.service }} Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.service }}/Dockerfile