name: Scan Images

on:
  workflow_call:
    inputs:
      sha_short:
        required: true
        type: string

permissions:
  contents: write


jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: skillpulse-backend
            folder: backend
          - image: skillpulse-frontend
            folder: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to docker hub 
        uses: docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USER }}/${{ matrix.image }}:${{ inputs.sha_short }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          ignore-unfixed: true

    
      # Only runs if scan passes
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: ${{ vars.DOCKERHUB_USER }}/${{ matrix.image }}:.*|image: ${{ vars.DOCKERHUB_USER }}/${{ matrix.image }}:${{ inputs.sha_short }}|g" k8s/${{ matrix.folder }}.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/${{ matrix.folder }}.yaml
          git diff --staged --quiet || git commit -m "ci: update ${{ matrix.image }} to ${{ inputs.sha_short }} [skip ci]"
          git pull --rebase origin feat-gitops
          git push