# API keys , credentials , sensative data
# used gitleaks 

name: Secrets scan

on:
  workflow_call:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: scan a secretes inside repo
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github actions manages this token you dont need to create secretes
